pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }


        stage('Test') {
            steps {
                sh 'mvn test'
            }

            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }


        stage('Docker Build') {
            steps {
                sh 'docker build -t hari-java-app:v2 .'
            }
        }


        stage('Docker Test Run') {
            steps {
                sh 'docker run --rm hari-java-app:v2'
            }
        }
    }
}
